name: Deploy
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'
      - name: Install Cleaver
        run: npm -g install cleaver
      - name: Generate Slide
        run: cleaver slide.md/*
      - name: Clean files
        run: rm -rf slide.md || rm ./*.md || rm *.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./
